# Generated by Django 2.1.7 on 2019-10-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=100)),
                ('profile_pic_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user_name', models.CharField(max_length=100)),
                ('gravatar_url', models.URLField()),
                ('issue_url', models.URLField()),
                ('state', models.CharField(max_length=50)),
                ('date_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IssueTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('issues', models.ManyToManyField(to='api.Issues')),
            ],
        ),
        migrations.CreateModel(
            name='PullReqeusts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user_name', models.CharField(max_length=100)),
                ('pull_request_url', models.URLField()),
                ('gravatar_url', models.URLField()),
                ('account_url', models.URLField()),
                ('state', models.CharField(max_length=50)),
                ('date_created', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PullRequestTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('pull_requests', models.ManyToManyField(to='api.PullReqeusts')),
            ],
        ),
        migrations.AddField(
            model_name='githubuser',
            name='issues',
            field=models.ManyToManyField(blank=True, to='api.Issues'),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='pulls',
            field=models.ManyToManyField(blank=True, to='api.PullReqeusts'),
        ),
    ]
